array: []
version: 3.2.1
woopra_config:
  domain: "adfinitas.fr"
  cookie_domain: ".adfinitas.fr"
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: dyngrid
    values:
      layout: formulaire
collections:
  dyngrid:
    output: true
    permalink: /:collection/:title/
    _hide_content: true
