array: []
version: 3.2.1
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: dyngrid
    values:
      layout: dyngrid
collections:
  dyngrid:
    output: true
    permalink: /:collection/:title/
    _hide_content: true
# Valeurs Frontmatter Cloudcannon
types:
  - fixe
  - addition
  - pourcentage
  - libre
# Configuration de iRaiser
iraiser_cid: 53
iraiser_url: 'don.spa.asso.fr'
# Configuration de Woopra
woopra_config:
  domain: "adfinitas.fr"
  cookie_domain: ".adfinitas.fr"
# Configuration de l'interaction Woopra de dyngrid
woopra_interaction: 'don-IMG_ete2015'
# Configuration des segments
noms:
  - "OPTIN"
  - "ADHERENT"
  - "DONATEUR"
  - "MIDDLE"
  - "GD"
nom_headers:
  - "OPTIN"
  - "ADHERENT"
  - "DONATEUR"
  - "MIDDLE"
  - "GD"
